
version: "3.9"

services:
  app:
    container_name: demo.app
    image: public.ecr.aws/r0u0o6g7/drepo:app
    restart: unless-stopped
    ports:
      - 80:5500
    networks:
      - demonet
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HOSTINGSTARTUPASSEMBLIES: Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation
      ASPNETCORE_URLS: http://0.0.0.0:5500

  prometheus:
    container_name: demo.prometheus
    image: prom/prometheus
    restart: always
    depends_on:
      - app
    ports:
      - 3001:9090
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml:Z
    networks:
      - demonet
  
  grafana:
    container_name: demo.grafana
    image: grafana/grafana-oss
    restart: always
    user: ${USER_ID}
    depends_on:
      - app
      - prometheus
    ports:
      - 3002:3000
    volumes:
      - /mnt/data/grafana:/var/lib/grafana
    networks:
      - demonet

networks:
  demonet:
    name: demonet