CREATE DATABASE $(MSSQL_DB);
GO

USE $(MSSQL_DB);
GO

CREATE LOGIN $(MSSQL_DB_USER) WITH PASSWORD = '$(MSSQL_DB_PASS)';
GO

CREATE USER $(MSSQL_DB_USER) FOR LOGIN $(MSSQL_DB_USER);
GO

ALTER SERVER ROLE sysadmin ADD MEMBER [$(MSSQL_DB_USER)];
GO