
version: "3.9"

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - 4000:8080
      - 50000:5000
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - demonet

networks:
  demonet:
    external: true